export const primaryColor = '#a0c8a5'
export const darkThemeHeaderColor = '#001529'
export const darkThemeFooterColor = '#001529'
export const darkThemeBodyColor = '#121212'
export const lightThemeHeaderColor = '#f9f9f9'
export const lightThemeFooterColor = '#f9f9f9'
export const lightThemeBodyColor = '#f5f5f5'
export const darkThemeIconFilter =
  'invert(100%) sepia(0%) saturate(3358%) hue-rotate(114deg) brightness(93%) contrast(85%)'
export const lightThemeIconFilter = 'none'
export const IconActiveFilter =
  'invert(87%) sepia(9%) saturate(770%) hue-rotate(76deg) brightness(87%) contrast(90%)'
export const githubUrl = 'https://github.com/llipengda/foodie-lion'
export const author = 'PDLi'
export const authorUrl = 'https://github.com/llipengda'
